//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cv.Mvc.Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReferans
    {
        public int ID { get; set; }
        public string Adsoyad { get; set; }
        public string Title { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Görsel { get; set; }
    }
}
